
package Horner;

import java.awt.Color;

/**
 *
 * @author SERINAC V.G
 */
public class WinEvaluacion extends javax.swing.JFrame {

    public WinEvaluacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        btntranparente();
    }
    
    public void btntranparente(){
        btnsalir.setOpaque(false);
        btnsalir.setContentAreaFilled(false);
        btnsalir.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public int grado;
    double Resultado1,Resultado2;
    public ClsPolinomio q;
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtDisplay = new javax.swing.JTextField();
        BtnGrado = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtnContador = new javax.swing.JButton();
        TxtSumaPotencias = new javax.swing.JTextField();
        TxtGrado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtValorx = new javax.swing.JTextField();
        TxtCoeficiente = new javax.swing.JTextField();
        BtnHorner = new javax.swing.JButton();
        BtnSumaPotencias2 = new javax.swing.JButton();
        TxtHorner = new javax.swing.JTextField();
        btnsalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblgrado = new javax.swing.JLabel();
        lblx = new javax.swing.JLabel();
        btnnuevo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtDisplay.setBackground(new java.awt.Color(204, 204, 204));
        TxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(TxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 260, -1));

        BtnGrado.setBackground(new java.awt.Color(51, 102, 255));
        BtnGrado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnGrado.setForeground(new java.awt.Color(255, 255, 255));
        BtnGrado.setText("Grado");
        BtnGrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnGradoMouseClicked(evt);
            }
        });
        BtnGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGradoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Métodos de evaluación");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        BtnContador.setBackground(new java.awt.Color(51, 102, 255));
        BtnContador.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnContador.setForeground(new java.awt.Color(255, 255, 255));
        BtnContador.setText("Coeficiente");
        BtnContador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnContadorMouseClicked(evt);
            }
        });
        getContentPane().add(BtnContador, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 100, -1));

        TxtSumaPotencias.setBackground(new java.awt.Color(204, 204, 204));
        TxtSumaPotencias.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(TxtSumaPotencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 92, -1));

        TxtGrado.setBackground(new java.awt.Color(204, 204, 204));
        TxtGrado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TxtGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtGradoActionPerformed(evt);
            }
        });
        getContentPane().add(TxtGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 45, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("X =");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        TxtValorx.setBackground(new java.awt.Color(204, 204, 204));
        TxtValorx.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(TxtValorx, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 43, -1));

        TxtCoeficiente.setBackground(new java.awt.Color(204, 204, 204));
        TxtCoeficiente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(TxtCoeficiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 48, -1));

        BtnHorner.setBackground(new java.awt.Color(51, 102, 255));
        BtnHorner.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnHorner.setForeground(new java.awt.Color(255, 255, 255));
        BtnHorner.setText("Horner");
        BtnHorner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnHornerMouseClicked(evt);
            }
        });
        getContentPane().add(BtnHorner, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        BtnSumaPotencias2.setBackground(new java.awt.Color(51, 102, 255));
        BtnSumaPotencias2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BtnSumaPotencias2.setForeground(new java.awt.Color(255, 255, 255));
        BtnSumaPotencias2.setText("Suma Potencias");
        BtnSumaPotencias2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSumaPotencias2MouseClicked(evt);
            }
        });
        BtnSumaPotencias2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSumaPotencias2ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSumaPotencias2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 130, -1));

        TxtHorner.setBackground(new java.awt.Color(204, 204, 204));
        TxtHorner.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(TxtHorner, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 92, -1));

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 60, 40));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel5.setText("f(x) = ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 90, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_pequeño.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 10, 250, 150));
        jLabel6.getAccessibleContext().setAccessibleName("lblsello");

        lblgrado.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        getContentPane().add(lblgrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 30, 20));

        lblx.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lblx.setText("X");
        getContentPane().add(lblx, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 20, 40));

        btnnuevo.setBackground(new java.awt.Color(51, 102, 255));
        btnnuevo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnnuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/xz.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGradoMouseClicked
        // TODO add your handling code here:
        grado=Integer.parseInt(TxtGrado.getText());
        q=new ClsPolinomio(grado+1);
        TxtGrado.setText(null);
        lblgrado.setText(" " + grado);
    }//GEN-LAST:event_BtnGradoMouseClicked

    private void BtnContadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnContadorMouseClicked
        // TODO add your handling code here:
        if(grado>0)
        {
            q.a(grado, Float.parseFloat(TxtCoeficiente.getText()));
            TxtCoeficiente.setText(null);
            grado-=1;
            lblgrado.setText(""+grado+"");
            TxtCoeficiente.requestFocus();

        }
        else

        {
            q.a(grado, Float.parseFloat(TxtCoeficiente.getText()));
            TxtDisplay.setText(q.ver());
        }
    }//GEN-LAST:event_BtnContadorMouseClicked

    private void TxtGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtGradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtGradoActionPerformed

    private void BtnHornerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHornerMouseClicked
        // TODO add your handling code here:
        Resultado1= q.Horner(Float.parseFloat(TxtValorx.getText()));
        TxtHorner.setText(Double.toString(Resultado1));
    }//GEN-LAST:event_BtnHornerMouseClicked

    private void BtnSumaPotencias2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSumaPotencias2MouseClicked
        // TODO add your handling code here:
        Resultado1= q.SumPotencias(Float.parseFloat(TxtValorx.getText()));
        TxtSumaPotencias.setText(Double.toString(Resultado1));
    }//GEN-LAST:event_BtnSumaPotencias2MouseClicked

    private void BtnSumaPotencias2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSumaPotencias2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSumaPotencias2ActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        WinEvaluacion nuevo=new WinEvaluacion();
        nuevo.setVisible(true);
        dispose();//cierra la ventana anterior
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void BtnGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinEvaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinEvaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinEvaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinEvaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinEvaluacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnContador;
    private javax.swing.JButton BtnGrado;
    private javax.swing.JButton BtnHorner;
    private javax.swing.JButton BtnSumaPotencias2;
    private javax.swing.JTextField TxtCoeficiente;
    private javax.swing.JTextField TxtDisplay;
    private javax.swing.JTextField TxtGrado;
    private javax.swing.JTextField TxtHorner;
    private javax.swing.JTextField TxtSumaPotencias;
    private javax.swing.JTextField TxtValorx;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblgrado;
    private javax.swing.JLabel lblx;
    // End of variables declaration//GEN-END:variables
}
